### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/DEV-Android#10]
**Is your feature request related to a problem? Please describe.**
The app currently does not notify users that they have received a notification. 

**Describe the solution you'd like**
This seems to require combination of JavaScript injection and 3rd party service like Firebase. It should also allow user to change their notification preference.

**Describe alternatives you've considered**
n/a

**Additional context**
[DEV's connect](https://dev.to/connect)'s message notification should be treated separately from a normal notification.

**Comment by c33s** [comment]
notification should work without google play services installed or at least the app should not quit if they are not installed (and also should not show a warning each time the app is opened).

the foss version of telegram is able to notify without google play services https://github.com/Telegram-FOSS-Team/Telegram-FOSS/

**Comment by sierisimo** [comment]
This should be easy to implement if #53 is added to the project.

**Comment by msfjarvis** [comment]
> the foss version of telegram is able to notify without google play services [Telegram-FOSS-Team/Telegram-FOSS](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/)

It uses a persistent foreground service for achieving that which has a significant battery consumption penalty. Using [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager.html) to fetch notifications at specific intervals is the most reasonable way I can think of right now that will work without GMS and won't burn through battery power.
