### ISSUE TITLE
Android app is broken

### ISSUE THREAD

**Issue by gautamkrishnar** [thepracticaldev/DEV-Android#105]
**Describe the bug**
Android app of dev.to is broken

**To Reproduce**
Download fresh app from the play store, open it.

**Expected behavior**
App should work properly

**Screenshots**
![Screenshot_20201107-180728.jpg](https://user-images.githubusercontent.com/8397274/98441460-71664880-2124-11eb-9c3a-2d44bbb6b549.jpg)

**Smartphone (please complete the following information):**

- Device: OnePlus 6T
- OS, version: Android 10
- Browser, version: n/a

**Additional context**

**Comment by fdoxyz** [comment]
Thank you for the report @gautamkrishnar. I wasn't able to reproduce on Samsung A21 with Android 10. It looks like on the Service Worker wasn't able to load in your case. Does the issue persist if you turn Airplane mode off/on or if you restart the app?

**Comment by gautamkrishnar** [comment]
Thanks @fdoxyz tired flight mode. Its working now. Closing this one.
