### ISSUE TITLE
Web Share API not working

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/DEV-Android#11]
**Describe the bug**
We use Web Share API to simplify sharing. It current works on browser but not in the app.

**To Reproduce**
1. Open the app.
2. Click on any article.
3. Click on triple dot on lower right corner. 
4. The Web Share API is not activated.

**Expected behavior**

**Screenshots**

**Left**: When WebShare isn't working. **Right**: When it is

<img height=400px src="https://user-images.githubusercontent.com/15793250/56536437-0fd38e80-652c-11e9-8bbf-f05a207be6ed.jpg"/><img height=400px src="https://user-images.githubusercontent.com/15793250/56536467-237ef500-652c-11e9-8b28-83415ca03422.jpg"/>

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: 9.0 "Pie"
 - Version: 1.0

**Additional context**
The [pull request](https://github.com/thepracticaldev/dev.to/pull/1524) for the implementation

**Comment by Glennmen** [comment]
After a quick search it seems that Android Webview or Android CustomTabs don't support `Navigator.share()`: https://bugs.chromium.org/p/chromium/issues/detail?id=765923

**Comment by maestromac** [comment]
Darn ☹️ . Thanks for that @Glennmen

**Comment by VarunBarad** [comment]
I've got an idea on this, I've opened a PR to include an Android <-> WebView bridge. This will allow us to invoke the native share sheet instead of the `Navigator.share()` which isn't supported in Android WebView.

If that is acceptable then we can start with this share issue to include more native code.

**Comment by alpkahveci** [comment]
> I've got an idea on this, I've opened a PR to include an Android <-> WebView bridge. This will allow us to invoke the native share sheet instead of the `Navigator.share()` which isn't supported in Android WebView.
> 
> If that is acceptable then we can start with this share issue to include more native code.



> After a quick search it seems that Android Webview or Android CustomTabs don't support `Navigator.share()`: https://bugs.chromium.org/p/chromium/issues/detail?id=765923

Does not it still support the web share api?

**Comment by fdoxyz** [comment]
Thank you for flagging this again @alpkahveci! Sorry for the slow response as well, our focus recently has been on other areas but this is an important feature I think could definitely use some attention.

@VarunBarad  I think your PR is the best solution for this. I know it's been a while, but would you be able to fix the merge conflicts for that? If not that's totally okay, would you be okay if we take over the PR and merge it? I'm leaving a small comment on that one for what we would need to update it.

**Comment by VarunBarad** [comment]
I would always be happy to help @fdoxyz though I am in middle of some-things right now and "might" not be able to get to fixing those merge-conflicts before the upcoming weekend. I would rather want to fix the merge conflicts myself.

PS: Thanks for the comment on PR about the required fixes 🙂

**Comment by fdoxyz** [comment]
That's great to hear @VarunBarad, thanks. Feel free to request my review or ping me when you're done
