### ISSUE TITLE
Signing in with Firefox as the default browser does not work

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/DEV-Android#12]
## Current Behavior
If my default browser is Firefox and I attempt to sign in on the DEV Android app, it opens a new tab in the actual Firefox app that's waiting to be opened.

## Expected Behavior
I should be able to properly go through the OAuth sign in flow with any browser.

**Comment by nourkilany** [comment]
I have the same problem. Moreover, when I try to login using either github or twitter it says csrf detected

**Comment by harnerdesigns** [comment]
Ran into a similar issue where the Twitter OAuth opens in Firefox, I sign in to twitter and it just redirects me to the Dev.To Homepage in Firefox (signed in as me) and doesn't sign me into the Native app.

**Comment by ross-holloway94** [comment]
I have this too. Also doesn't work if I launch the Github deeplink via the FastHub android app.

**Comment by MateuszBelczowski** [comment]
I'm also experiencing this one. After clicking "Sign in with Twitter" button, Twitter login page opens in Firefox and after filling the credentials, I'm not being redirected to the dev.to app

**Comment by zhanghanduo** [comment]
Same problem. Log in via Firefox, edge, fastHub have the same issue.

**Comment by DevAspirerKlaus** [comment]
I've removed OAuth authorization in Twitter and/or GitHub and still can't login on the app.

**Comment by MateuszBelczowski** [comment]
I can confirm that new version resolves this problem, thanks :tada:

**Comment by harnerdesigns** [comment]
Updated App to the latest version from the app store and the issue has been resolved.

**Comment by maestromac** [comment]
Thank you for being patient everyone! Please give latest version a try and let us know if the issue still persist.

Resolved with https://github.com/thepracticaldev/DEV-Android/pull/21
