### ISSUE TITLE
Update Adaptive Icon

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-Android#13]
**Describe the bug**
Reported to yo@dev.to: 

Found a bug, your adaptive icon has a no bueno background!

Ideally your background should be completely black and your foreground should be transparent with white DEV text. Otherwise when I shake the app on the home screen the attached happens, haha

**Screenshots**
![](https://cl.ly/6ae278e7e6b3/download/Image%202019-04-24%20at%2010.11.38%20AM.png)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/DEV-Android/pull/19
