### ISSUE TITLE
Title "MY READING LIST (EMPTY) is clipped on the navigation menu

### ISSUE THREAD

**Issue by siddeshpillai** [thepracticaldev/DEV-Android#17]
**UI bug**
MY READING LIST (EMPTY) text is clipped on the navigation menu in Pixel 2.

**Steps to Reproduce**
1. Open the app
2. Click on the top left hamburger button or swipe from the left edge of the screen to open the navigation menu
3. See screenshot section

**Expected behavior**
Either the text show flow to the next line or set the text pixel size based on the device's scale factor.

**Screenshots**
![Screenshot_20190424-112229](https://user-images.githubusercontent.com/4101783/56684719-30632c00-6685-11e9-958b-a3e78cfb7edb.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: 9.0 "Pie"

**Comment by maestromac** [comment]
Thank you for the issue report. I think changing that to `MY READING LIST (0)` is also viable but it will be done with our web app.

**Comment by fdoxyz** [comment]
Closing as this area has been redesigned
