### ISSUE TITLE
Moving `main url` out of `strings.xml`

### ISSUE THREAD

**Issue by VarunBarad** [thepracticaldev/DEV-Android#20]
**Is your feature request related to a problem? Please describe.**
The main url for the website (https://dev.to) is stored as a string resource. It currently works because the url is not being used at any place where a string-resource can't be accessed. But later as things are moved over to native code, there will be requirement to use that url where it is not possible to access a string resource.
For example, Retrofit is the most popular networking library and it becomes easier to integrate Retrofit when we don't have the base-url in a string resource.

**Describe the solution you'd like**
We move the main url of the website to a `Constants.kt` file in which we store all such urls.

**Additional context**
The url I am mentioning is located in the linked file: [https://github.com/thepracticaldev/DEV-Android/blob/master/app/src/main/res/values/strings.xml](https://github.com/thepracticaldev/DEV-Android/blob/master/app/src/main/res/values/strings.xml)

**Comment by jhw866** [comment]
This is a good idea but I think the placement of the url should be elsewhere. I don't foresee it changing but having the url defined in the build.gradle and assigning during the build to be retrieved from the BuildConfig might be a better option. This allows the app to be a little more modular and still defines the url in a constants file that can be retrieved by anyone (android and java code). Just thinking out loud though.

**Comment by maestromac** [comment]
Thanks for pointing this out @VarunBarad. I agree with @jhw866 : having it assigned at the higher level sounds more impactful.

**Comment by VarunBarad** [comment]
I too agree with @jhw866 and suggest that we define both a `BuildConfig` (that value will be available in Java/Kotlin code) and a `resourceConfig` (this value will be available to access in xml resource files).
If everything is fine with this approach then I can make the change and open a PR.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/DEV-Android/pull/27
