### ISSUE TITLE
Image Upload Tool Not Working

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/DEV-Android#29]
We received this bit of feedback about the image upload tool:

"Hello, I came here to report some problems I saw on the Android app
First: the image upload tool is not working, as you might imagine since the app also does not request permission to use internal storage."

**Comment by Bhupesh-V** [comment]
Hey @michael-tharrington a similar issue #18 is already there

**Comment by michael-tharrington** [comment]
Oh whoops! I should've taken a deeper look. Thanks @Bhupesh-V ... I'm going to close this one.
