### ISSUE TITLE
Unable to upload profile image in android mobile app

### ISSUE THREAD

**Issue by dev-arjunan** [thepracticaldev/DEV-Android#33]
**Describe the bug**
I'm unable to upload new profile image from android app.

**To Reproduce**

1. Go to 'top right corner and tap on profile'
2. Click on 'settings'
3. Scroll down to 'Profile Image section'
4. Tap on "Upload" button

**Expected behavior**
It should open up window to choose image from gallery

**Screenshots**
![Screenshot_2019-05-31-19-29-41-697_to dev dev_android](https://user-images.githubusercontent.com/50161510/58711178-8c834380-83db-11e9-9bae-c61f09280740.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [Redmi note 6 pro]
- OS: [Android Oreo 8.1.0]
- App: Latest version

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by maestromac** [comment]
Thanks for this report @dev-arjunan ! Sorry about confusing issue transfer I did. This is already address in the new 1.2 released in beta channel. I'll keep you updated when the it's released to production.

**Comment by maestromac** [comment]
The new version was just released. Please give latest version a try (could take 1-2 hours for it to be publicly available) and let me know if the problem still persists!

**Comment by arjunans** [comment]
Hi team, 
I have updated app now.  When I tap on upload button,  I'm able to get gallery and select image but it's throwing error when I submit to save profile image. 

Error message that I got "Profile image image size Should be less than or equal to  4096x4096. You can see " Image" Word twice in error message and why do mobile image need 4096 size? 
![Screenshot_2019-06-04-07-20-26-524_to dev dev_android](https://user-images.githubusercontent.com/15280629/58845726-dd27c480-8699-11e9-98b6-15fc89a094e2.png)

**Comment by maestromac** [comment]
Hmm that is interesting. This might be specific to the android app. 

Can you please create a separate issue for that bug @arjunans ?
