### ISSUE TITLE
Clear back history on tapping home link

### ISSUE THREAD

**Issue by robertoissc** [thepracticaldev/DEV-Android#35]
**Is your feature request related to a problem? Please describe.**
When navigating through the app the back history keeps growing infinitely without clear hierarchy.

**Describe the solution you'd like**
It'd make sense to me to clear back history if I click on the home link on the top bar as I'm returning to the entry point of the application.

I'd like to implement this if this gets approved. :)

**Comment by maestromac** [comment]
Thanks for the issue @robertoissc . I agree with this. Approved!

**Comment by robertoissc** [comment]
Thanks @maestromac!
WIP
