### ISSUE TITLE
Adding Detekt

### ISSUE THREAD

**Issue by joanb** [thepracticaldev/DEV-Android#45]
I think it would be nice to have [detekt](https://github.com/arturbosch/detekt) code analysis for the Kotlin code.

It would have at least the following beneifts:
 - Code style standarization
 - Typical static code analysis stuff: complexity, code smells, etc
 - Easier to digest code reviews
 - Ensure a minimum of quality

For that being posible, it would be nice to trigger detekt when a PR is generated, and prevent it from being merged until the static analysis marks it as good.

If interested, I would gladly start doing a first version of the configuration :)

**Comment by maestromac** [comment]
Yes! this would be great

**Comment by sierisimo** [comment]
Detekt is a great tool and adding configurations is really smooth. If some help is needed, count me in!

**Comment by xuhaibahmad** [comment]
Haven't seen any progress on this one yet. Is it okay if I create a PR for this?

**Comment by joanb** [comment]
Sorry i was on vacation. I'm glad it's been approved :)
