### ISSUE TITLE
Image uploading still doesn't work

### ISSUE THREAD

**Issue by Delta456** [thepracticaldev/DEV-Android#51]
**Android Version**: 5.0 Lollipop

**Version**: 4.2

Posting an image doesn't work after the fix done in `version 4.2`.

**Comment by subbramanil** [comment]
@Delta456 Can you add bit more description? Screen, Steps to reproduce, etc.,

**Comment by Delta456** [comment]
@subbramanil Normal steps on how to upload an image?

**Comment by manan30** [comment]
@Delta456 is it applicable to all the views wherever image uploading is possible or just a particular view?

**Comment by Delta456** [comment]
@manan30 Applicable to all views

**Comment by manan30** [comment]
So yesterday I tried replicating this issue but unfortunately wasn't able to do so. Is this happening only on Android 5? I had tested this issue on Android 10 and it seems to be working fine.

**Comment by subbramanil** [comment]
Is this still an open issue?

**Comment by Delta456** [comment]
It works now!
