### ISSUE TITLE
Authentication error with GitHub

### ISSUE THREAD

**Issue by fdoxyz** [thepracticaldev/DEV-Android#73]
**Describe the bug**
GitHub Authentication method is not working in the app due to a recent change in the Manifest file

**To Reproduce**
In production version `1.3.0` log in with GitHub authentication

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: 9
 - Version: `1.3.0`

Got a PR for this in a minute for review

**Comment by fdoxyz** [comment]
The error was introduced due to a change in the Manifest [here](https://github.com/thepracticaldev/DEV-Android/commit/ccf4aa250f478380d3fb99c1073459d19135707b)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/DEV-Android/pull/74
