### ISSUE TITLE
Duplicate .gitignore files in the repository

### ISSUE THREAD

**Issue by Rec0iL99** [thepracticaldev/DEV-Android#78]
**Describe the bug**
Currently there are various different duplicate .gitignore files in the whole repository.
* app/.gitignore
* data/.gitignore
* baseui/.gitignore
* buildSrc/.gitignore

**Expected behavior**
There should be just one root .gitignore file.

**Comment by Rec0iL99** [comment]
@fdoxyz I would like to work on this issue.

**Comment by fdoxyz** [comment]
Hello @Rec0iL99 thank you for the report! I can't think of a reason why multiple `.gitignore` files are necessary, it would be easier to navigate if everything was in a single one.

I'm assigning you the issue, feel free to send in a PR or ping me if you need any help 🙂

**Comment by Rec0iL99** [comment]
@fdoxyz thanks a lot for assigning this issue to me. I have opened a PR linking ths issue.
