### ISSUE TITLE
Login via Twitter issue 

### ISSUE THREAD

**Issue by shubhamjadhav36** [thepracticaldev/DEV-Android#82]
**Describe the bug**
When i try to login via twitter on Dev App it will open up chrome browser, then from browser I'm able to login via twitter nd able to use the Dev on web.
But however when i close the browser and open my Dev app it wont recognise me. It will again asks for login .
If i try to login again then it will open browser and cycle goes on...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: samsung galaxy a5
 - OS: android 8.0.0
 - Version: 8.0.0

**Additional context**

**Comment by fdoxyz** [comment]
Thank you for the report @shubhamjadhav36!

I can't reproduce using a Samsung S8 with Android 9, but I'll look further into this soon.
