### ISSUE TITLE
Can't play video on google pixel

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-Android#86]
**Describe the bug**

**To Reproduce**

1. Visit https://dev.to/bytesized/byte-sized-episode-1-grace-hopper-3bp9
2. Try to play video
3. See error 

**Screenshots**

![Screenshot_20200611-162518](https://user-images.githubusercontent.com/14931921/84517673-9d78bd00-ac9d-11ea-9324-8c0593e9dbd1.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 10

**Comment by fdoxyz** [comment]
Android's WebView implementation has problems reproducing Video from the HTML `video` tag. There doesn't seem to be a straightforward fix for this at the moment using "stock configuration" options from the WebView itself.

Possible solutions I can think of:
1. Customize our `CustomWebViewClient` to handle pages that have the HTML `video` tag and handle the playback in a separate view with a separate native Fragment/Activity. I found [this project](https://github.com/cprcrack/VideoEnabledWebView) (older and now unmaintained) that took a stab at this, might be valuable to take inspiration from it
1. Use the `AndroidWebViewBridge` interface to stop the HTML `video` tag from attempting to play the video and instead handle an incoming message from JavaScript that will trigger the video playback using native APIs

At the moment option 2. seems like a better solution in my eyes.

In either case it's important to consider we already have [ExoPlayer](https://exoplayer.dev/) in the project so we could relatively easy handle the video playback using their [PlayerView](https://exoplayer.dev/ui-components.html#playerview)

**Comment by maestromac** [comment]
@fdoxyz Yeah option 2 sounds good.
