### ISSUE TITLE
App crashing upon trying to login

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-Android#98]
**Describe the bug**

A user has written in to share that whenever they try to login, it'll ask for credentials but then the app will close. Happening for both Twitter & Github.

**To Reproduce**
Try logging in with the below device.

**Smartphone (please complete the following information):**
 - Huawei Mate 10 lite with 8.0.0

**Comment by ItzaMi** [comment]
Thank you, @jessleenyc , I was the one that sent the email
Here's a gif that shows what's happening (sorry for the low quality)
As you can see, when you choose your credentials, it just closes the app

![devLogin](https://user-images.githubusercontent.com/30603437/93022481-8c638300-f5e1-11ea-987e-93cdfe38330f.gif)

**Comment by maestromac** [comment]
@ItzaMi Thank you for your patience. We just released the fix to beta track. You can expect production release in the upcoming days.

**Comment by fdoxyz** [comment]
The fix was shipped in the latest release `1.4.2`
